modLoader="javafml"
loaderVersion="[36,)"
license="PGGRgames Recources license"

[[mods]]
modId="advanced_mod"
version="Update 1 2021/2022"
displayName="Advanced mod"
credits="..."
displayURL="http://pggrgames.tk"
authors="GVspeed aka Yannick Galow"
description='''
Follow on github for Updates
'''

[[dependencies.advanced_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




